### ISSUE TITLE
blazorhosted template is no longer available in CLI

### ISSUE THREAD

**Issue by ghost** [Apress/blazor-revealed#3]
Following the steps to create MyFirstBlazor app, it is mentioned to user blazorhosted, which is no longer available. As of now, the only two available templates are blazorserver and blazorwasm.

**Comment by MohammadMQ** [comment]
Please refer to page no in the book.
Blazor "concepts" is being constantly renamed and remodified, which is ofcourse frustrating. However blazorwasm is currently what would be considered blazor client in the book.

**Comment by ghost** [comment]
Which page number?

**Comment by MohammadMQ** [comment]
The page number of the book "blazor revealed" (ISBN 978-1-4842-4343-5), where it is mentioned to user blazorhosted.
